name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Red Hat registry
      with:
        username: ${{ secrets.RH_REGISTRY_USERNAME }}
        password: ${{ secrets.RH_REGISTRY_PASSWORD }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
